name: test-wasm

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download Risc0
        run: |
          curl -L https://risczero.com/install | bash
          echo "/home/runner/.risc0/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.risc0/bin:$PATH"
      - name: Install Risc0
        run: /home/runner/.risc0/bin/rzup install
      - name: Check out
        uses: actions/checkout@v4
        with:
          repository: risc0/risc0
      - name: Test
        working-directory: examples/wasm
        run: |
          ls .
          cargo run --release
